# ---------------------------
# WebhookX configuration file
# ---------------------------

log:
  file: /dev/stdout
  level: debug   # supported values are debug, info, warn, and error.
  format: text  # supported values are text and json

database:
  host: localhost
  port: 5432
  username: webhookx
  password:
  database: webhookx

redis:
  host: localhost
  port: 6379
  password:
  database: 0



#------------------------------------------------------------------------------
# ADMIN
#------------------------------------------------------------------------------

admin:
  listen: 127.0.0.1:8080

#------------------------------------------------------------------------------
# WORKER
#------------------------------------------------------------------------------

worker:
  enabled: false
  deliverer:
    timeout: 60000

#------------------------------------------------------------------------------
# PROXY
#------------------------------------------------------------------------------
proxy:
  #listen: 127.0.0.1:8081
  timeout_read: 10                  # read timeout (in seconds), 0 indicates unlimited.
  timeout_write: 60                 # write timeout (in seconds), 0 indicates unlimited.
  max_request_body_size: 1048576
  response:
    code: 200
    content-type: application/json
    body: '{"message": "OK"}'

  queue:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0

tracing:
#  enabled: false // do we need this?
  service_name: WebhookX
  global_attributes:
    foo: bar
    baz: buz
  captured_request_headers:
  captured_response_headers:
  safe_query_params:
  add_internals: true
  sampling_rate: 1
  opentelemetry:
    http:
      endpoint: http://jaeger:4318/v1/traces
      headers:
        foo: bar
        baz: buz
#    grpc:
#      endpoint: localhost:4317
#      headers:
#        foo: bar
#        baz: buz
#      insecure: true
